routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Auth::routes(['register' => false]);

Route::middleware(['auth', 'encerrado'])->group(function () {
    Route::get('/', 'ProjetoController@index')->name('inicio');
    Route::get('/sucesso', 'ProjetoController@sucesso'); // editar registro
    Route::get('/congratulations', 'ProjetoController@congratulations'); // editar registro
    Route::get('/projeto/edit/{id}/box/{box}', 'ProjetoController@setBox'); // editar registro
    Route::resource('projeto', 'ProjetoController');
    Route::resource('curso', 'CursoController');
    Route::get('/mapa', 'MapaController@showMapa')->name('mapa');
    Route::get('/mapa/sala/{id}', 'MapaController@showSala')->name('sala');
    Route::get('/mapa/bloco', 'MapaController@showBloco')->name('bloco');
    Route::get('/mapa/bloco/{id}', 'MapaController@showBlocoCurso')->name('bloco');
});
Route::group(['middleware' => ['auth', 'admin']], function () {
    Route::get('/admin', 'AdminController@index'); // editar registro
    Route::get('/etiquetas', 'AdminController@relEtiquetas'); // editar registro
    Route::get('/aprovar', 'AdminController@relEtiquetas'); // editar registro
    Route::get('/aprovar/{id}', 'AdminController@aprovar'); // editar registro
    Route::get('/reprovar/{id}', 'AdminController@reprovar'); // editar registro
    Route::get('/projetos', 'AdminController@projetos'); // editar registro
    Route::get('/usuarios', 'AdminController@usuarios'); // editar registro
});

app/Projeto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Projeto extends Model
{
    protected $table = "projeto";

    protected $fillable = ['nome',
        'curso_id',
        'usuario_id',
        'box',
        'turma',
        'integrantes',
        'orientadores',
        'email',
        'arquivo',
        'status'];

    public static function rules()
    {
        return [
            'curso_id' => 'required|integer',
            'usuario_id' => 'required|integer',
            'box' => 'required|integer',
            'turma' => 'required|integer',
            'orientadores' => 'required|min:3|max:255',
            'email' => 'required|min:3|max:255|unique:expoceep_projetos',
            'arquivo' => 'required|min:3|max:255',
        ];
    }

    public static function rulesUpdate()
    {
        return [
            'curso_id' => 'required|integer',
            'usuario_id' => 'required|integer',
            'box' => 'required|integer',
            'turma' => 'required|integer',
            'orientadores' => 'required|min:3|max:255',
            'email' => 'required|min:3|max:255|unique:expoceep_projetos',
            'arquivo' => 'required|min:3|max:255',
        ];
    }

    public function curso()
    {
        return $this->belongsTo('App\Curso', 'curso_id');
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'usuario_id');
        //return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ProjetoController.php
<?php

namespace App\Http\Controllers;

use App\Curso;
use App\Http\Requests\ProjetoRequest;
/* use Illuminate\Http\File;*/
use App\Projeto;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ProjetoController extends Controller
{
    public function index()
    {
        $projeto = Projeto::where('usuario_id', '=', Auth::id())->get();
        //return response()->json($projeto);
        return view('projeto.home', compact('projeto'));
    }

    public function show($id)
    {
        $projeto = projeto::find($id);
        if (empty($projeto)) {
            return '<div class="alert alert-danger">Erro: objeto não encontrado</div>';
        }
        //return response()->json($projeto);
        return view('projeto.show', compact('projeto'));
    }

    public function update(ProjetoRequest $request, $id)
    {
        $request->validate([
            'arquivo' => 'max:5120', //5MB
        ]);

        $path = $request->arquivo->store('arquivos');
        $url = Storage::url($path);
        $dados = $request->all();

        $projeto = projeto::find($id);
        $dados["usuario_id"] = Auth::user()->id;
        $dados["arquivo"] = $url;
        $projeto->update($dados);

        return redirect()->action('ProjetoController@index')->withInput($request->only('nome'));
    }

    public function sucesso()
    {
        return view('projeto.success');
    }

    public function congratulations()
    {
        return view('projeto.congratulations');
    }

    public function setBox($id, $box)
    {
        $projeto = projeto::find($id);

        $projeto->box = $box;
        $projeto->sala = session('projeto_sala');

        $projeto->save();

        return redirect()->action('ProjetoController@congratulations');
    }

    public function getBoxOcupado($sala)
    {
        $box = DB::table('projeto')->where('sala', '=', $sala)->get();

        return $box();
    }

    public function store(ProjetoRequest $request)
    {
        $request->validate([
            'arquivo' => 'max:5120', //5MB
        ]);

        $path = $request->arquivo->store('arquivos');
        $url = Storage::url($path);
        $dados = $request->all();

        $dados["usuario_id"] = Auth::user()->id;
        $dados["arquivo"] = $url;

        $projeto = projeto::create($dados);

        // Store a piece of data in the session...
        session(['projeto_id' => $projeto->id]);
        session(['projeto_idcurso' => $projeto->curso_id]);
        //return response()->json($projeto);
        return redirect()->action('ProjetoController@sucesso');
    }

    public function destroy($id)
    {
        $projeto = projeto::find($id);
        $projeto->delete();
        //return response()->json($projeto);
        return redirect()->action('ProjetoController@index');
    }

    public function create()
    {
        $cursos = Curso::all();
        return view('projeto.create-edit', compact('cursos'));
    }

    public function edit($id)
    {
        $cursos = Curso::all();
        $projeto = projeto::find($id);
        if (empty($projeto)) {
            return '<div class="alert alert-danger">Erro: objeto não encontrado</div>';
        }
        //return response()->json($projeto);
        return view('projeto.create-edit', compact('projeto', 'cursos'));
    }
}

resources/views/projeto/congratulations.blade.php
@extends('layouts.app')
@section('content')
    <h1 class="text-center alert alert-success"> Parabéns! Seu box foi escolhido.</h1>

    <br>

    <h2>Esta inscrição está concuída.</h2>
    <blockquote class="blockquote">
        <p class="mb-5 mt-5">Você poderá alterar alguns dados de seu projeto assim como o seu box acessando a página inicial.</p>
    </blockquote>
    <div class="text-center">
        <a href="/" class="btn btn-lg btn-large btn-success"> Concluído </a>
    </div>
    @stop

resources/views/projeto/create-edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Informações do projeto</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif


                    @if ($errors->any())
                    <div class='alert alert-danger'>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    @if (isset($projeto))
                    <form method="post" action="{{route('projeto.update', ['id'=> $projeto ->id])}}" enctype="multipart/form-data">
                        {!! method_field('PUT')!!}
                        @else
                        <form action="{{route('projeto.store')}}" method='post' enctype="multipart/form-data">
                        @endif

                        {{ csrf_field() }}
                            <div class='form-group'>
                                <label>Nome do projeto</label>
                                <input name='nome' value='{{$projeto->nome or old('nome')}}' class='form-control'/>
                            </div>
                            <div class='form-group'>
                                <label>Nome do projeto</label>
                                <select name="area" class="form-control" required>
                                <option value="">Área do conhecimento</option>
                            @php
                            
                            $areas = array(
                                '1' => 'Ciências Agrárias',
                                '2' => 'Ciências Biológicas',
                                '3' => 'Ciências da Saúde',
                                '4' => 'Ciências Exatas e da Terra',
                                '5' => 'Ciências Humanas',
                                '6' => 'Ciências Sociais',
                                '7' => 'Engenharias e suas Aplicações'
                            );
                            @endphp
                            @foreach ($areas as $key => $value) 

                                <option value="{{$key}}" {{ (old("area") == $key ? "selected":"") }}

                                    @if(isset($projeto) && ($key == $projeto->area))
                                        selected
                                    @endif
    
                                    >{{$value}}
                            @endforeach
                            
                            </select>
                        </div>
                        <div class='form-group'>
                            <label>Selecione o curso</label>
                            <select name="curso_id" class='form-control'>
                            <option value="">Escolha</option>
                            @foreach ($cursos as $c)
                                <option value="{{$c->id}}" {{ (old("curso_id") == $c->id ? "selected":"") }}

                                @if(isset($projeto) && ($c->id == $projeto->curso_id))
                                    selected
                                @endif

                                >{{$c->nome}}
                            </option>
                            @endforeach
                            </select>
                            </div>
                            <div class='form-group'>
                                <label>Selecione a turma</label>
                                <select name='turma' class='form-control'>
                                    <option value="">Escolha</option>
                                    <option {{ (old("turma") == "1° Ano A" ? "selected":"") }}
                                    @if(isset($projeto) && ("1° Ano A" == $projeto->turma))
                                        selected
                                    @endif
                                    value="1° Ano A">1° Ano A</option>
                                    <option {{ (old("turma") == "2° Ano A" ? "selected":"") }}
                                    @if(isset($projeto) && ("2° Ano A" == $projeto->turma))
                                        selected
                                    @endif
                                    value="2° Ano A">2° Ano A</option>
                                    <option {{ (old("turma") == "3° Ano A" ? "selected":"") }}

                                    @if(isset($projeto) && ("3° Ano A" == $projeto->turma))
                                        selected
                                    @endif
                                    value="3° Ano A">3° Ano A</option>
                                    <option {{ (old("turma") == "4° Ano A" ? "selected":"") }}
                                    @if(isset($projeto) && ("4° Ano A" == $projeto->turma))
                                        selected
                                    @endif
                                    value="4° Ano A">4° Ano A</option>

                                    <option {{ (old("turma") == "1° Ano B" ? "selected":"") }}
                                    @if(isset($projeto) && ("1° Ano B" == $projeto->turma))
                                        selected
                                    @endif
                                    value="1° Ano B">1° Ano B</option>
                                    <option {{ (old("turma") == "2° Ano B" ? "selected":"") }}
                                    @if(isset($projeto) && ("2° Ano B" == $projeto->turma))
                                        selected
                                    @endif
                                    value="2° Ano B">2° Ano B</option>
                                    <option {{ (old("turma") == "3° Ano B" ? "selected":"") }}
                                    @if(isset($projeto) && ("3° Ano B" == $projeto->turma))
                                        selected
                                    @endif
                                    value="3° Ano B">3° Ano B</option>
                                    <option {{ (old("turma") == "4° Ano B" ? "selected":"") }}
                                    @if(isset($projeto) && ("4° Ano B" == $projeto->turma))
                                        selected
                                    @endif
                                    value="4° Ano B">4° Ano B</option>

                                    <option {{ (old("turma") == "1° Ano C" ? "selected":"") }}
                                    @if(isset($projeto) && ("1° Ano C" == $projeto->turma))
                                        selected
                                    @endif
                                    value="1° Ano B">1° Ano C</option>
                                    <option {{ (old("turma") == "2° Ano C" ? "selected":"") }}
                                    @if(isset($projeto) && ("2° Ano C" == $projeto->turma))
                                        selected
                                    @endif
                                    value="2° Ano B">2° Ano C</option>
                                    <option {{ (old("turma") == "3° Ano C" ? "selected":"") }}
                                    @if(isset($projeto) && ("3° Ano C" == $projeto->turma))
                                        selected
                                    @endif
                                    value="3° Ano B">3° Ano C</option>
                                    <option {{ (old("turma") == "4° Ano C" ? "selected":"") }}
                                    @if(isset($projeto) && ("4° Ano C" == $projeto->turma))
                                        selected
                                    @endif
                                    value="4° Ano B">4° Ano C</option>

                                    <option {{ (old("turma") == "1° Semestre" ? "selected":"") }}
                                    @if(isset($projeto) && ("1° Semestre" == $projeto->turma))
                                        selected
                                    @endif
                                    value="1° Semestre">1° Semestre</option>
                                    <option {{ (old("turma") == "2° Semestre" ? "selected":"") }}
                                    @if(isset($projeto) && ("2° Semestre" == $projeto->turma))
                                        selected
                                    @endif
                                    value="2° Semestre">2° Semestre</option>
                                    <option {{ (old("turma") == "3° Semestre" ? "selected":"") }}
                                    @if(isset($projeto) && ("3° Semestre" == $projeto->turma))
                                        selected
                                    @endif
                                    value="3° Semestre">3° Semestre</option>
                                    <option {{ (old("turma") == "4° Semestre" ? "selected":"") }}
                                    @if(isset($projeto) && ("4° Semestre" == $projeto->turma))
                                        selected
                                    @endif
                                    value="4° Semestre">4° Semestre</option>
                                </select>
                                <!-- <input value='{{$projeto->turma or old('turma')}}' class='form-control'/> -->
                            </div>
                            <!--<div class='form-group'>
                                <label>Integrantes</label>
                                <textarea name='integrantes' class='form-control'>{{$projeto->integrantes or old('integrantes')}}</textarea></div> -->                            
                            <div class='form-group'>
                                <label>Orientadores</label>
                                <textarea name='orientadores' class='form-control'>{{$projeto->orientadores or old('orientadores')}}</textarea>
                            </div>
                            <div class='form-group'>
                                <label>Email de contato</label>
                                <input name='email' type="email" value='{{$projeto->email or old('email')}}' class='form-control'/>
                            </div>
                            <div class='form-group'>
                                <label>Selecione o arquivo</label>
                                <input name='arquivo' type='file' value='{{$projeto->arquivo or old('arquivo')}}' class='form-control'/>
                            </div>
                            @if (isset($dados))
                                <button type="submit" class="btn btn-primary btn-block">Alterar</button>
                            @else
                                <button type="submit" class="btn btn-primary btn-block">Enviar</button>
                            @endif
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/projeto/edit.blade.php
@extends('layouts.app')
@section('content')
<!-- @if(empty($dados)) -->
<div class='alert alert-danger'>
Erro dados nulos
</div>
<!-- @else -->
<h1>Editar projeto</h1>
<form action='/projeto/{{$dados->id}}' method='post'>
{{ csrf_field() }}
{{ method_field('PUT') }}
 <div class='form-group'>
                   <label>id</label>
                   <input name='id' value='{{$dados->id}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>nome</label>
                   <input name='nome' value='{{$dados->nome}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>curso_id</label>
                   <input name='curso_id' value='{{$dados->curso_id}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>idusuario</label>
                   <input name='idusuario' value='{{$dados->idusuario}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>box</label>
                   <input name='box' value='{{$dados->box}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>turma</label>
                   <input name='turma' value='{{$dados->turma}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>integrantes</label>
                   <input name='integrantes' value='{{$dados->integrantes}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>orientadores</label>
                   <input name='orientadores' value='{{$dados->orientadores}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>email</label>
                   <input name='email' value='{{$dados->email}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>arquivo</label>
                   <input name='arquivo' value='{{$dados->arquivo}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>data_hora</label>
                   <input name='data_hora' value='{{$dados->data_hora}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>created_at</label>
                   <input name='created_at' value='{{$dados->created_at}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>updated_at</label>
                   <input name='updated_at' value='{{$dados->updated_at}}' class='form-control'/>
                </div>
<button type='submit'
class='btn btn-primary btn-block'>Alterar</button>
</form>
@endif
@stop

resources/views/projeto/home.blade.php
@extends('layouts.app')
@section('content')
    <a href='docs/Modelo_projeto_pesquisa_escolar.docx'>Modelo de projeto de pesquisa escolar</a><br>
    <a href='docs/Modelo_projeto_iniciacao_cientifica.docx'>Modelo de projeto de iniciação científica</a><br>
    <a href='docs/Orientacoes_inicicao_cientifica.doc'>Orientaçãoes para projetos de iniciação científica</a><br>
    <a href='docs/Modelo_banner_novo.ppt'>Modelo de banner</a><br>
    <h1>Meus projetos

        {{--@if(count($projeto)==0)--}}
            <a class='btn btn-primary' href='{{action("ProjetoController@create")}}'>
                Enviar projeto
                </a>
        {{--@endif--}}
    </h1>
<table class='table table-striped table-bordered table-hover'>
    <tr><th>Situação</th><th>Nome</th><th>Curso</th><th>Sala</th><th>Box</th><th>Turma</th><th>Orientadores</th><th>Arquivo</th><th colspan='4'>Ações</th>
        @foreach ($projeto as $d)
            <tr>
            <td>{{$d->status}}</td>
            <!-- <td>{{$d->id}}</td> -->
            <td>{{$d->nome}}</td>
            <td>{{$d->curso["nome"]}}</td>
            <td>{{$d->sala}}</td>
            <td>{{$d->box}}</td>
            <td>{{$d->turma}}</td>
            <!--<td>{{$d->integrantes}}</td>-->
            <td>{{$d->orientadores}}</td>
           <!--  <td>{{$d->email}}</td> -->
            <td><a class="btn btn-outline-primary" href="{{$d->arquivo}}">Download</a></td>
           <!--  <td>{{$d->created_at}}</td>
            <td>{{$d->updated_at}}</td> -->
      <!--   <td>
            <a class='btn btn-success' href='{{action('ProjetoController@show', $d->id)}}'>
                <i class='material-icons'>info</i>
            </a>
        </td> -->
        <td>
        <form action='/projeto/{{$d->id}}' method='post' onsubmit="return confirm('Tem certeza que deseja excluir?')">
            {{ csrf_field() }}
            {{ method_field('DELETE') }}
            <button class='btn btn-danger'>
                <i class='material-icons'>Excluir</i>
            </button>
        </form>
    </td>
    <td>
        <a class='btn btn-warning' href='{{action('ProjetoController@edit', $d->id)}}'>
            <i class='material-icons'>Alterar</i>
        </a>
    </td>
    {{--
    <td>
        <a class='btn btn-secondary' href='{{action('MapaController@showBlocoCurso', $d->id)}}'>
            <i class='material-icons'>Escolher box</i>
        </a>
    </td>--}}
    </tr>
@endforeach
</table>
@stop

resources/views/projeto/show.blade.php
@extends('layouts.app')
@section('content')
    <h1>Detalhes: </h1>
    <ul>
        <li><b>id:</b>{{$projeto->id}}</li>
        <li><b>nome:</b>{{$projeto->nome}}</li>
        <li><b>curso_id:</b>{{$projeto->curso_id}}</li>
        <li><b>idusuario:</b>{{$projeto->idusuario}}</li>
        <li><b>box:</b>{{$projeto->box}}</li>
        <li><b>turma:</b>{{$projeto->turma}}</li>
        <li><b>integrantes:</b>{{$projeto->integrantes}}</li>
        <li><b>orientadores:</b>{{$projeto->orientadores}}</li>
        <li><b>email:</b>{{$projeto->email}}</li>
        <li><b>arquivo:</b>{{$projeto->arquivo}}</li>
        <li><b>data_hora:</b>{{$projeto->data_hora}}</li>
        <li><b>created_at:</b>{{$projeto->created_at}}</li>
        <li><b>updated_at:</b>{{$projeto->updated_at}}</li>
    </ul>@stop

resources/views/projeto/success.blade.php
@extends('layouts.app')
@section('content')
    <h1 class="text-center alert alert-success"> Parabéns! Seu projeto foi incluído.</h1>

    <br>
    <a href="/projeto" class="btn btn-lg btn-large btn-info"> Voltar para meus projetos </a>
<!--
    <h2>Agora você pode escolher o local de exposição.</h2>
    <blockquote class="blockquote">
        <p class="mb-5 mt-5">Você poderá escolher seu box de exposição dentro de uma área pré estabelecida para seu curso. Escolha primeiro uma sala dentre as disponíveis e depois escolha o box que deseja.</p>
    </blockquote>
    <div class="text-center">
        <a href="/mapa/bloco" class="btn btn-lg btn-large btn-danger"> Escolher meu box agora </a>
    </div>-->
    @stop