routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Auth::routes(['register' => false]);

Route::middleware(['auth', 'encerrado'])->group(function () {
    Route::get('/', 'ProjetoController@index')->name('inicio');
    Route::get('/sucesso', 'ProjetoController@sucesso'); // editar registro
    Route::get('/congratulations', 'ProjetoController@congratulations'); // editar registro
    Route::get('/projeto/edit/{id}/box/{box}', 'ProjetoController@setBox'); // editar registro
    Route::resource('projeto', 'ProjetoController');
    Route::resource('curso', 'CursoController');
    Route::get('/mapa', 'MapaController@showMapa')->name('mapa');
    Route::get('/mapa/sala/{id}', 'MapaController@showSala')->name('sala');
    Route::get('/mapa/bloco', 'MapaController@showBloco')->name('bloco');
    Route::get('/mapa/bloco/{id}', 'MapaController@showBlocoCurso')->name('bloco');
});
Route::group(['middleware' => ['auth', 'admin']], function () {
    Route::get('/admin', 'AdminController@index'); // editar registro
    Route::get('/etiquetas', 'AdminController@relEtiquetas'); // editar registro
    Route::get('/aprovar', 'AdminController@relEtiquetas'); // editar registro
    Route::get('/aprovar/{id}', 'AdminController@aprovar'); // editar registro
    Route::get('/reprovar/{id}', 'AdminController@reprovar'); // editar registro
    Route::get('/projetos', 'AdminController@projetos'); // editar registro
    Route::get('/usuarios', 'AdminController@usuarios'); // editar registro
});

app/Curso.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Curso extends Model
{
    protected $table = "curso";
    protected $fillable = ['nome'];

    public static function rules() {
        return [
            'nome' => 'required|min:3|max:255'
        ];
    }

    public static function rulesUpdate($id = '') {
        return [
            'nome' => 'min:3|max:255'
        ];
    }
}

app/Http/Controllers/CursoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CursoRequest;
use App\Curso;

class CursoController extends Controller
{
    public function index(){
        $cursos = Curso::all();
        //return response()->json($Curso);
        return view('curso.home', compact('cursos'));
    }

    public function show($id){
        $curso = Curso::find($id);
        if(empty($Curso)) {
            return '<div class="alert alert-danger">Erro: objeto não encontrado</div>';
        }
        //return response()->json($Curso);
        return view('curso.show', compact('curso'));
    }

    public function update(CursoRequest $request, $id){
        $curso = Curso::find($id);
        $curso ->update($request->all());
        // return response()->json($Curso);
        return redirect()->action('CursoController@index')->withInput($request->only('nome'));
    }


    public function store(CursoRequest $request){
        $curso = Curso::create($request->all());
        //return response()->json($Curso);
        return redirect()->action('CursoController@index')->withInput($request->only('nome'));
    }

    public function destroy($id){
        $curso = Curso::find($id);
        $curso ->delete();
        //return response()->json($Curso);
        return redirect()->action('CursoController@index');
    }

    public function create(){
        return view('curso.create-edit');
    }

    public function edit($id){
        $curso = Curso::find($id);
        if(empty($curso)) {
            return '<div class="alert alert-danger">Erro: objeto não encontrado</div>';
        }
        //return response()->json($Curso);
        return view('curso.create-edit', compact('curso'));
    }
}

resources/views/curso/create-edit.blade.php
@extends('layouts.app')
@section('content')
<h1>{{isset($curso) ? 'Editar curso' : 'Cadastrar curso'}}</h1>
@if ($errors->any())
<div class='alert alert-danger'>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
@if (isset($curso))
<form method="post" action="{{route('curso.update', ['id'=> $curso ->id])}}" enctype="multipart/form-data">
    {!! method_field('PUT')!!}
    @else
    <form action="{{route('curso.store')}}" method='post'>
    @endif

    {{ csrf_field() }}
        <div class='form-group'>
            <label>nome</label>
            <input name='nome' value='{{$curso->nome or old('nome')}}' class='form-control'/>
        </div>
@if (isset($dados))
    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
@else
    <button type="submit" class="btn btn-primary btn-block">Enviar</button>
@endif
</form>
@stop

resources/views/curso/edit.blade.php
@extends('layouts.app')
@section('content')
<!-- @if(empty($dados)) -->
<div class='alert alert-danger'>
Erro dados nulos
</div>
<!-- @else -->
<h1>Editar curso</h1>
<form action='/curso/{{$dados->id}}' method='post'>
{{ csrf_field() }}
{{ method_field('PUT') }}
 <div class='form-group'>
                   <label>id</label>
                   <input name='id' value='{{$dados->id}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>nome</label>
                   <input name='nome' value='{{$dados->nome}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>situacao</label>
                   <input name='situacao' value='{{$dados->situacao}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>created_at</label>
                   <input name='created_at' value='{{$dados->created_at}}' class='form-control'/>
                </div>
 <div class='form-group'>
                   <label>updated_at</label>
                   <input name='updated_at' value='{{$dados->updated_at}}' class='form-control'/>
                </div>
<button type='submit'
class='btn btn-primary btn-block'>Alterar</button>
</form>
@endif
@stop

resources/views/curso/home.blade.php
@extends('layouts.app')
@section('content')
    <h1>Listagem de curso</h1>
<a class='btn btn-warning' href='{{action("CursoController@create")}}'>
Novo
</a>
<table class='table table-striped table-bordered table-hover'>
    <tr><th>id</th><th>nome</th><th>situacao</th><th>created_at</th><th>updated_at</th>
        @foreach ($cursos as $d)
            <tr>
            <td>{{$d->id}}</td>
            <td>{{$d->nome}}</td>
            <td>{{$d->situacao}}</td>
            <td>{{$d->created_at}}</td>
            <td>{{$d->updated_at}}</td>
        <td>
            <a class='btn btn-success' href='{{action('CursoController@show', $d->id)}}'>
                <i class='material-icons'>info</i>
            </a>
        </td>
        <td>
        <form action='/curso/{{$d->id}}' method='post'>
            {{ csrf_field() }}
            {{ method_field('DELETE') }}
            <button class='btn btn-danger'>
                <i class='material-icons'>delete</i>
            </button>
        </form>
    </td>
    <td>
        <a class='btn btn-warning' href='{{action('CursoController@edit', $d->id)}}'>
            <i class='material-icons'>edit</i>
        </a>
    </td>
    </tr>
@endforeach
</table>
@stop

resources/views/curso/show.blade.php
@extends('layouts.app')
@section('content')
    <h1>Detalhes: </h1>
    <ul>
        <li><b>id:</b>{{$curso->id}}</li>
        <li><b>nome:</b>{{$curso->nome}}</li>
        <li><b>situacao:</b>{{$curso->situacao}}</li>
        <li><b>created_at:</b>{{$curso->created_at}}</li>
        <li><b>updated_at:</b>{{$curso->updated_at}}</li>
    </ul>@stop